[Desktop Entry]
Type=X-GNOME-Metatheme
Name=agua-negra-Turquoise-Numix
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=agua-negra-Turquoise-Numix
GtkTheme=agua-negra-Turquoise-Numix
IconTheme=agua-negra-Turquoise-Numix
MetacityTheme=agua-negra-Turquoise-Numix
